### ISSUE TITLE
Travis-CI test failure Python 3.5 -- test_discover_subpackage 

### ISSUE THREAD

**Issue by sjagoe** [scalative/haas#176]
I am not able to reproduce this failure on Python 3.5 locally or the Python 3.5.6 Python docker image using the same steps as executed by travis.

```
======================================================================
ERROR: test_discover_subpackage (haas.plugins.tests.test_discoverer.TestDiscoverFilteredTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scalative/haas/haas/plugins/tests/test_discoverer.py", line 422, in test_discover_subpackage
    top_level_directory=self.tmpdir,
  File "/home/travis/build/scalative/haas/haas/plugins/discoverer.py", line 219, in discover
    pattern=pattern)
  File "/home/travis/build/scalative/haas/haas/plugins/discoverer.py", line 256, in discover_by_module
    dirname, basename = os.path.split(module.__file__)
AttributeError: module 'tests' has no attribute '__file__'
```

**Comment by sjagoe** [comment]
Resolved in #175.
