### ISSUE TITLE
Coveralls client no longer supports Python 2.6

### ISSUE THREAD

**Issue by sjagoe** [scalative/haas#180]
The coveralls client code uses `'{}'.format()` style formatting, without numbered placeholders, which is not allowed in Python 2.6. This style is used in multiple places in the client code.

```
Submitting coverage to coveralls.io...
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6.9/bin/coveralls", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/coveralls/cli.py", line 77, in main
    result = coverallz.wear()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/coveralls/api.py", line 168, in wear
    json_string = self.create_report()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/coveralls/api.py", line 182, in create_report
    data = self.create_data()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/coveralls/api.py", line 237, in create_data
    self._data.update(git_info())
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/coveralls/git.py", line 68, in git_info
    'id': gitlog('%H'),
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/coveralls/git.py", line 29, in gitlog
    '--pretty=format:{}'.format(fmt))
ValueError: zero length field name in format
```

**Comment by sjagoe** [comment]
Neither do we.
